name: Daily Python Script

on:
  schedule:
    # Run daily at 10:00 AM IST (which is 4:30 AM UTC)
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode and write service account key
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" | base64 -d > service_account.json

      - name: Create .env file from secrets
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "APP_PASSWORD=${{ secrets.APP_PASSWORD }}" >> .env
          echo "GEMINI_APIKEY=${{ secrets.GEMINI_APIKEY }}" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=service_account.json" >> .env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
          echo "DATASET_ID=${{ secrets.DATASET_ID }}" >> .env
          echo "RAW_TABLE_NAME=${{ secrets.RAW_TABLE_NAME }}" >> .env
          echo "VENTUREBEAT_AI_URL=${{ secrets.VENTUREBEAT_AI_URL }}" >> .env

      - name: Run script
        run: python scraper/main.py

      - name: Clean up sensitive files
        run: rm -f service_account.json .env
